language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-plode-basic' ]; then cd .. && eval "mv $currentfolder generator-plode-basic" && cd generator-plode-basic; fi

